name: "File Exists"
description: "Checks if a file exists in the repository"
inputs:
  file:
    description: "The path to the file to check"
    required: true
secrets:
  THEALBERTDEVBOT_APP_ID:
    required: true
  THEALBERTDEVBOT_SECRET_KEY:
    required: true
runs:
  using: "composite"
  steps:
    - name: Get GitHub App token
      uses: actions/create-github-app-token@v2
      id: app-token
      with: 
        app-id: ${{ secrets.THEALBERTDEVBOT_APP_ID }}
        private-key: ${{ secrets.THEALBERTDEVBOT_SECRET_KEY }}
        owner: ${{ github.repository_owner }}
    - name: Check if file exists
      uses: actions/github-script@v7
      env:
        FILE_PATH: ${{ inputs.file }}
      with:
        github-token: ${{ steps.app-token.outputs.token }}
        script: |
          const fs = require('fs');
          const path = require('path');
          const filePath = path.join(process.env.GITHUB_WORKSPACE, process.env.FILE_PATH);

          if (!fs.existsSync(filePath)) {
            core.setFailed(`❌ File does not exist: ${filePath}`);
            return;
          }

          console.log(`✅ File exists: ${filePath}`);
